### ISSUE TITLE
Building on OS X 10.11 with Xcode 8 fails

### ISSUE THREAD

**Issue by JCount** [saldl/saldl#8]
### saldl -v
```
saldl v34 (https://saldl.github.io)

Copyright (C) 2014-2016 Mohammad AlSaleh.
Free use of this software is granted under the terms of
the GNU Affero General Public License (AGPL).

Built against: libcurl 7.43.0
Loaded: libcurl 7.43.0 (SecureTransport)
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp.
```
### Describe the issue / How to reproduce
Building on OS X 10.11 El Capitan with Xcode 8 fails due to a clock_gettime error. This is due to the fact that the unitary SDK model provides symbols that are defined in the Xcode 8 SDK headers used for both 10.11 and 10.12, but only implemented in the system libraries found on 10.12.

How to reproduce: attempt to compile on OS X 10.11 using Xcode 8.
### log output (if needed)
http://pastebin.com/GUPc7QaQ

-----
If you have need of any more information I am happy to provide it.

**Comment by MoSal** [comment]
```
[12/17] Compiling src/utime.c
../src/utime.c:27:13: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  int ret = clock_gettime(CLOCK_MONOTONIC_RAW, &tp);
            ^
../src/utime.c:27:27: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
  int ret = clock_gettime(CLOCK_MONOTONIC_RAW, &tp);
                          ^
2 errors generated.
```

Hmm.

[This is the code in question](https://github.com/saldl/saldl/blob/fc1911b71066e2ad5d8e8daf1bf08104d890c946/src/utime.c#L22):

``` C
#ifdef HAVE_CLOCK_MONOTONIC_RAW

#include <time.h>
double saldl_utime() {
  struct timespec tp;
  int ret = clock_gettime(CLOCK_MONOTONIC_RAW, &tp);

  if (ret) {
    fatal(FN, "clock_gettime() failed, %s.", strerror(errno));
  }

  return tp.tv_sec + tp.tv_nsec/1000.0/1000.0/1000.0;
}

#elif defined(HAVE_GETTIMEOFDAY)
```
This code shouldn't have been used unless you have `-DHAVE_CLOCK_MONOTONIC_RAW=1`, and you do.

That define should only be set if [this test](https://github.com/saldl/saldl/blob/fc1911b71066e2ad5d8e8daf1bf08104d890c946/wscript#L287) succeeds:

``` python
   conf.check_cc(fragment=
            '''
            #include <time.h>
            int main() {
              struct timespec tp;
              clock_gettime(CLOCK_MONOTONIC_RAW, &tp);
              return 0;
            }
            ''',
            define_name="HAVE_CLOCK_MONOTONIC_RAW",
            msg = "Checking for clock_gettime() with CLOCK_MONOTONIC_RAW support",
            mandatory=False)
```

So, the real question is, how is this test succeeding?

**Comment by JCount** [comment]
This test succeeds because the SDK in Xcode 8 uses the same headers for both 10.11 and 10.12, however, only 10.12 actually has _clock_gettime implemented in system libraries. 
```
$ grep clock_gettime MacOSX.sdk/usr/include/time.h
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
__uint64_t clock_gettime_nsec_np(clockid_t __clock_id);
```
10.11 uses weak symbols instead for those that are defined in the SDK headers but not actually implemented in system libraries.
```
$ grep 'weak$os10.11' MacOSX.sdk/usr/lib/system/libsystem_c.tbd
    symbols:         [ '$ld$weak$os10.11$_basename_r', '$ld$weak$os10.11$_clock_getres',
                       '$ld$weak$os10.11$_clock_gettime', '$ld$weak$os10.11$_clock_settime',
                       '$ld$weak$os10.11$_dirname_r', '$ld$weak$os10.11$_getentropy',
                       '$ld$weak$os10.11$_mkostemp', '$ld$weak$os10.11$_mkostemps',
```

**Comment by MoSal** [comment]
@JCount 

**Note**: Changing `#ifdef HAVE_CLOCK_MONOTONIC_RAW` to `#if 0` is a work-around that should work.
But I'd still like to know what's going on.

-----

* The error is happening at the compile stage, not the linking stage. It's not finding the function
  in the headers at all!
* The test actually compiles, links, and runs, and it's succeeding somehow!

Steps that could help clarify the situation:
* The full output of `./waf configure -v`
* The full output of `./waf build -v`

Are there any compile-flags that are present when `Checking for clock_gettime() with CLOCK_MONOTONIC_RAW support`, but not when building? Or vise versa.

What happens if you compile the test stand-alone:
* With no flags?
* With the flags present at configure time?
* With the flags present at build time?

**Comment by ilovezfs** [comment]
To reproduce the problem outside of Homebrew:

```
export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
export MACOSX_DEPLOYMENT_TARGET=10.11
./waf configure
./waf build
```

**Comment by MoSal** [comment]
@ilovezfs 

Unfortunately, I don't have access to to an El Capitan system. And I don't know how I'm supposed to use
Xcode (I never used OSX day-to-day).

I managed to get a Sierra VM running. And then installed Xcode. And then ran your commands.
And everything worked as expected (with the test succeeding).

If there is nothing else I can do. And there are no more logs for me to look at. I will special-case OSX to
use `gettimeofday()` in the build script.

**Comment by ilovezfs** [comment]
@MoSal This is a 10.11 + Xcode 8 specific problem. It doesn't affect 10.12 or < 10.11.

**Comment by MoSal** [comment]
@JCount @ilovezfs 

I reproduced the error caused by a lazy symbol binding failure at run-time. Compilation and linking
succeeded as expected. So, the log you provided me still doesn't make sense.

Anyway, it turns out I remembered wrong. `waf` does not execute code fragment checks by default.
Setting a simple `execute` flag causes the check to fail, which is the behavior we want.

**Comment by ilovezfs** [comment]
@MoSal yep. Fix works! Thanks for digging into this.

> Compilation and linking succeeded as expected. So, the log you provided me still doesn't make sense.

SDKROOT is likely the magic sauce that is making it seem weird to you.

**Comment by ilovezfs** [comment]
@MoSal do you mind tagging a new release for this, or should we backport your fix to v34 downstream?

**Comment by MoSal** [comment]
@ilovezfs 
Just released `v35`.
